/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Estructuras.*;
import Modelo.*;
import Control.*;
import java.awt.Dimension;
/**
 *
 * @author Santiago Mendoza
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    BuscarPanel bp;
    AgregarPanel ap;
    AlquilarPanel alp;
    LinkedList listaVehiculos;
    AdministrarVehiculo admivehi;
    
    public Principal() {
        initComponents();
        bp= new BuscarPanel();
        ap= new AgregarPanel();
        alp= new AlquilarPanel();
        
        //this.setSize(750, 550); //dimensiones fijas
        //editar dimensiones minimas permitidas
        //this.setMinimumSize(new Dimension(450,400));
        
        
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar3 = new javax.swing.JMenuBar();
        buscarMenu = new javax.swing.JMenu();
        agregarMenu = new javax.swing.JMenu();
        alquilarMenu = new javax.swing.JMenu();

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ALQUILER DE VEHÍCULOS");

        panelPrincipal.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        panelPrincipal.add(jPanel1, java.awt.BorderLayout.CENTER);

        buscarMenu.setText("Buscar");
        buscarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buscarMenuMousePressed(evt);
            }
        });
        jMenuBar3.add(buscarMenu);

        agregarMenu.setText("Agregar");
        agregarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                agregarMenuMousePressed(evt);
            }
        });
        jMenuBar3.add(agregarMenu);

        alquilarMenu.setText("Alquilar");
        alquilarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                alquilarMenuMousePressed(evt);
            }
        });
        jMenuBar3.add(alquilarMenu);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buscarMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMenuMousePressed
        // TODO add your handling code here:
        bp.setAdministrarVehiculo(admivehi);
        panelPrincipal.setVisible(false);
        panelPrincipal.removeAll();
        panelPrincipal.add(bp);
        panelPrincipal.setVisible(true);
        System.out.println(admivehi.listaDeVehiculos.size());
        System.out.println(admivehi.vehiculosAlquilados.size());
    }//GEN-LAST:event_buscarMenuMousePressed

    private void agregarMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMenuMousePressed
        // TODO add your handling code here:
        ap.setAdministrarVehiculo(admivehi);
        panelPrincipal.setVisible(false);
        panelPrincipal.removeAll();
        panelPrincipal.add(ap);
        panelPrincipal.setVisible(true);
        System.out.println(admivehi.listaDeVehiculos.size());
        System.out.println(admivehi.vehiculosAlquilados.size());
    }//GEN-LAST:event_agregarMenuMousePressed

    private void alquilarMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alquilarMenuMousePressed
        // TODO add your handling code here:
        alp.setAdministrarVehiculo(admivehi);
        panelPrincipal.setVisible(false);
        panelPrincipal.removeAll();
        panelPrincipal.add(alp);
        panelPrincipal.setVisible(true);
        System.out.println(admivehi.listaDeVehiculos.size());
        System.out.println(admivehi.vehiculosAlquilados.size());
    }//GEN-LAST:event_alquilarMenuMousePressed

    public void setAdministrarVehiculos(AdministrarVehiculo adv){
        this.admivehi=adv;
    }  
    public void setListaVehiculos(LinkedList lista){
        this.listaVehiculos=lista;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu agregarMenu;
    private javax.swing.JMenu alquilarMenu;
    private javax.swing.JMenu buscarMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelPrincipal;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    // End of variables declaration//GEN-END:variables
}
